apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: albanmurtezaj/nodejs-demo-app:latest
          ports:
            - containerPort: 80
